repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: bash -c "cd docker && poetry run black ."
        language: system
        types: [python]
      - id: flake8
        name: flake8
        entry: bash -c "cd docker && poetry run flake8"
        language: system
        types: [python]
