name: CI
on: [ push ]
env:
  PYTHON_VERSION: 3.9.5

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    defaults:
      run:
        working-directory: docker

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Setup Poetry
        uses: moneymeets/action-setup-poetry@master

      - name: Restore virtualenv from Poetry cache
        uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ env.PYTHON_VERSION }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Lint and test
        run: |
          poetry run flake8
          poetry run coverage run -m pytest
          poetry run coverage report --fail-under 31

      - name: Export image name
        run: |
          # For branch names other than master (e.g. feature/test), append last branch name component (test) to the tag
          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
            export TAG=latest
          else
            export TAG=${GITHUB_REF##*/}
          fi

          echo "IMAGE=moneymeets/ghd:$TAG" >> $GITHUB_ENV

      - name: Build image
        run: docker build --build-arg PYTHON_VERSION=${{ env.PYTHON_VERSION }} -t $IMAGE .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish image
        run: docker push $IMAGE
