name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    defaults:
      run:
        working-directory: docker

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_REGISTRY: moneymeets/ghd

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.5

      - name: Setup Poetry
        uses: moneymeets/action-setup-poetry@master

      - name: Cache Poetry virtualenv
        uses: actions/cache@v2
        id: poetry-cache
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: |
          poetry install

      - name: Lint and test
        run: |
          poetry run flake8
          poetry run coverage run -m pytest
          poetry run coverage report --fail-under 31

      - name: Build and publish image
        run: |
          # For branch names other than master (e.g. feature/test), append last branch name component (test) to the tag
          export TAG=${GITHUB_REF##*/}
          docker build -t $DOCKER_REGISTRY:latest .
          [ "$TAG" != "latest" ] && docker tag $DOCKER_REGISTRY:latest $DOCKER_REGISTRY:$TAG
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push $DOCKER_REGISTRY
